# Generated by rust2rpm 18
Name:           pop-launcher
Version:        1.0.3
Release:        %autorelease
Summary:        Modular IPC-based desktop launcher service

License:        GPLv3 and ASL 2.0 and MIT

%global gituser pop-os
%global gitrepo launcher
%global commit  170c6bbfb25c0683c4e70701a1da88613968cf2a

URL:            https://github.com/%{gituser}/%{gitrepo}
Source0:        %{url}/archive/%{commit}/%{gitrepo}-%{commit}.tar.gz

ExclusiveArch:  %{rust_arches}
%if %{__cargo_skip_build}
BuildArch:      noarch
%endif

BuildRequires:  cargo
BuildRequires:  gtk3-devel
BuildRequires:  openssl-devel
BuildRequires:  rust-const_format rust-const_format_proc_macros
BuildRequires:  rust-darling rust-darling_core rust-darling_macro
BuildRequires:  rust-pretty_assertions
BuildRequires:  rust-serde_with1.9.4 rust-serde_with_macros

Requires:       gnome-shell-extension-pop-shell
Requires:       libqalculate
Requires:       fd-find
Requires:       qalc

%description
Modular IPC-based desktop launcher service, written in Rust. Desktop launchers
may interface with this service via spawning the pop-launcher process and
communicating to it via JSON IPC over the stdin and stdout pipes. The launcher
service will also spawn plugins found in plugin directories on demand, based on
the queries sent to the service.

%prep
%autosetup -n %{gitrepo}-%{commit} -p1

%build
%make_build compile

%install
%make_install

%files
%license COPYING
%doc README.md debian/changelog

%changelog
* Thu Nov 04 2021 Aiden Langley <me@aidenlangley.com> - 1.0.3
- Initial package
