# Generated by rust2rpm 18
%global debug_package %{nil}

Name:       pop-launcher
Version:    1.0.3
Release:    %autorelease
Summary:    Modular IPC-based desktop launcher service

License:    GPLv3 and ASL 2.0 and MIT

ExclusiveArch:  %{rust_arches}

%global gituser pop-os
%global gitrepo launcher
%global commit  170c6bbfb25c0683c4e70701a1da88613968cf2a

URL:        https://github.com/%{gituser}/%{gitrepo}
Source0:    %{url}/archive/%{commit}/%{gitrepo}-%{commit}.tar.gz

# https://bradthemad.org/tech/notes/patching_rpms.php
# diff -uNr launcher launcher.p/ > launcher.patch
Patch0:     %{gitrepo}-170c6bbfb25c0683c4e70701a1da88613968cf2a.patch

BuildRequires:  cargo gtk3-devel openssl-devel
Requires:       gnome-shell-extension-pop-shell

Recommends: libqalculate qalc fd-find

Provides:   pop-launcher
Provides:   qalc
Provides:   find

%description
Modular IPC-based desktop launcher service, written in Rust. Desktop launchers
may interface with this service via spawning the pop-launcher process and
communicating to it via JSON IPC over the stdin and stdout pipes. The launcher
service will also spawn plugins found in plugin directories on demand, based on
the queries sent to the service.

%prep
%autosetup -n %{gitrepo}-%{commit} -p1

%build
%make_build

# https://docs.fedoraproject.org/en-US/packaging-guidelines/RPMMacros/
%install
%make_install LIB_PATH="%{_libdir}"

%files
%license COPYING
%doc README.md debian/changelog
%{_binpath}/%{name}
%dir %{_libdir}/%{name}/plugins/calc/
%dir %{_libdir}/%{name}/plugins/desktop_entries/
%dir %{_libdir}/%{name}/plugins/files/
%dir %{_libdir}/%{name}/plugins/find/
%dir %{_libdir}/%{name}/plugins/pop_shell/
%dir %{_libdir}/%{name}/plugins/pulse/
%dir %{_libdir}/%{name}/plugins/recent/
%dir %{_libdir}/%{name}/plugins/scripts/
%dir %{_libdir}/%{name}/plugins/terminal/
%dir %{_libdir}/%{name}/plugins/web/
%dir %{_libdir}/%{name}/scripts/session/
%dir %{_libdir}/%{name}/scripts/system76-power/

%changelog
* Thu Nov 04 2021 Aiden Langley <me@aidenlangley.com> - 1.0.3-170c6bbfb25c0683c4e70701a1da88613968cf2a
- Initial package
