# Generated by rust2rpm 18
%bcond_without check
%global debug_package   %{nil}
%global crate           pop-launcher
%global gituser         pop-os
%global gitrepo         launcher
%global commit          04d6653b0b42fa3e4c113cd9fb37ff084f9d9588

Name:       rust-%{crate}
Version:    04d6653b0b42fa3e4c113cd9fb37ff084f9d9588
Release:    1%{?dist}
Summary:    Library for writing plugins and frontends for %{crate}

# Upstream license specification: GPL-3.0-only
License:    GPLv3 and ASL 2.0 and MIT
# FIXME: Upstream uses unknown SPDX tag GPL-3.0-only!
URL:        https://github.com/%{gituser}/%{gitrepo}.git
Source:     https://github.com/%{gituser}/%{gitrepo}/archive/%{commit}/%{gitrepo}-%{commit}.tar.gz

ExclusiveArch:  %{rust_arches}
%if %{__cargo_skip_build}
BuildArch:      noarch
%endif

BuildRequires:  rust-packaging
BuildRequires:  rust-const_format
Requires:       gnome-shell-extension-pop-shell
Requires:       libqalculate
Requires:       xdg-utils
Requires:       glibc-common

Provides:       libqalculate qalc

%global _description %{expand:
Library for writing plugins and frontends for %{crate}.}

%description %{_description}

%package    devel
Summary:    %{summary}
BuildArch:  noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files      devel
%license    COPYING
%doc        README.md debian/changelog
%{cargo_registry}/%{crate}-%{version_no_tilde}/

%package    -n %{crate}+default-devel
Summary:    %{summary}
BuildArch:  noarch

%description -n %{crate}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files  -n %{crate}+default-devel
%ghost  %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%prep
%autosetup  -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%files
%license    COPYING

%changelog
* Sun Oct 31 2021 nedia <me@aidenlangley.com> - 1.0.1-1
- Initial package
