# Generated by rust2rpm 18
%bcond_without check
%global debug_package %{nil}

%global crate pop-launcher-git

Name:           rust-%{crate}
Version:        1.0.2
Release:        %autorelease
Summary:        Library for writing plugins and frontends for pop-launcher

License:        GPLv3 and ASL 2.0 and MIT

%global     gituser     pop-os
%global     gitrepo     launcher
%global     commit      04d6653b0b42fa3e4c113cd9fb37ff084f9d9588

URL:    https://github.com/%{gituser}/%{gitrepo}
Source: https://github.com/%{gituser}/%{gitrepo}/archive/%{commit}/%{gitrepo}-%{commit}.tar.gz

ExclusiveArch:  %{rust_arches}
%if %{__cargo_skip_build}
BuildArch:      noarch
%endif

BuildRequires:  rust-packaging

%global _description %{expand:
Library for writing plugins and frontends for pop-launcher.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%license COPYING
%doc README.md debian/changelog
%{cargo_registry}/%{crate}-%{version_no_tilde}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
